# menu and terminal
bind=SUPER,d,spawn,rofi -show drun
bind=SUPER,Return,spawn,alacritty

# noctalia
exec-once=noctalia

# File Manager
bind=SUPER,f,spawn,thunar

# emacs
exec-once=emacs --daemon
# T14 bind
bind=none,XF86FAVORITES,spawn,emacsclient -c
# Logitech K360 keyboard bind
bind=none,XF86CALCULATOR,exec emacsclient -c

# Browser
bind=SUPER,b,spawn,env MOZ_ENABLE_WAYLAND=1 librewolf

# Proton VPN
assign [app_id="proton.vpn.app.gtk"] 9

# Kanshi (Display Manager)
exec-once=kanshi

# fcitx5
exec-once=fcitx5

# syncthing
exec-once=/mnt/backup/Downloads/Syncthing/syncthing
