# noctalia
exec-once=noctalia

# emacs
exec-once=emacs --daemon
# T14 bind
bind=XF86FAVORITES,spawn,emacsclient -c
# Logitech K360 keyboard bind
bind=XF86CALCULATOR,spawn,emacsclient -c

# Proton VPN
assign [app_id="proton.vpn.app.gtk"] 10

# Kanshi (Display Manager)
exec-once=kanshi, kanshi