# Key Bindings
# key name refer to `xev` or `wev` command output,
# mod keys name: super,ctrl,alt,shift,none

# reload config
bind=SUPER,r,reload_config

# exit
bind=SUPER,m,quit
bind=SUPER,q,killclient,