# Overview Setting
hotarea_size=10
enable_hotarea=-1
ov_tab_mode=0
ov_no_resize=1
overviewgappi=5
overviewgappo=30

# Axis Bindings
axisbind=SUPER,UP,viewtoleft_have_client
axisbind=SUPER,DOWN,viewtoright_have_client

source=~/.config/mango/noctaliabinds.conf
source=~/.config/mango/eyecandy.conf
source=~/.config/mango/inputs.conf
source=~/.config/mango/workspaces.conf
source=~/.config/mango/apps.conf
source=~/.config/mango/binds.conf
source=~/.config/mango/layouts.conf
source=~/.config/mango/misc.conf


source=~/.config/mango/noctalia.conf
