# Overview Setting
hotarea_size=10
enable_hotarea=-1
ov_tab_mode=0
ov_no_resize=1
overviewgappi=5
overviewgappo=30

# Axis Bindings
axisbind=SUPER,UP,viewtoleft_have_client
axisbind=SUPER,DOWN,viewtoright_have_client

source=~/.config/mango/configs/eyecandy.conf
source=~/.config/mango/configs/inputs.conf
source=~/.config/mango/configs/workspaces.conf
source=~/.config/mango/configs/apps.conf
source=~/.config/mango/configs/binds.conf
source=~/.config/mango/configs/layouts.conf
source=~/.config/mango/configs/misc.conf
source=~/.config/mango/configs/dmsbinds.conf

# DMS Include Configs
source=./dms/outputs.conf
