# Default Layouts
# tile,scroller, grid, deck, monocle, center_tile, vertical_tile, vertical_scroller, dwindle, fair, vertical_fair
tagrule=id:1,layout_name:scroller
tagrule=id:2,layout_name:scroller
tagrule=id:3,layout_name:scroller
tagrule=id:4,layout_name:scroller
tagrule=id:5,layout_name:scroller
tagrule=id:6,layout_name:scroller
tagrule=id:7,layout_name:scroller
tagrule=id:8,layout_name:scroller
tagrule=id:9,layout_name:scroller

# switch layout
bind=SUPER,n,switch_layout

# Mouse Button Bindings
# btn_left and btn_right can't bind none mod key
mousebind=SUPER,btn_left,moveresize,curmove
mousebind=NONE,btn_middle,togglemaximizescreen,0
mousebind=SUPER,btn_right,moveresize,curresize

# Scroller Layout Setting
scroller_structs=20
scroller_default_proportion=0.8
scroller_focus_center=0
scroller_prefer_center=0
edge_scroller_pointer_focus=1
edge_scroller_focus_allow_speed=0.0
scroller_default_proportion_single=1.0
scroller_proportion_preset=0.5,0.8,1.0

# scroller layout
#bind=ALT,e,set_proportion,1.0
#bind=ALT,x,switch_proportion_preset,
#bind=alt+super+ctrl,Left,scroller_stack,left
#bind=alt+super+ctrl,Right,scroller_stack,right
#bind=alt+super+ctrl,Up,scroller_stack,up
#bind=alt+super+ctrl,Down,scroller_stack,down

# Master-Stack Layout Setting
new_is_master=1
default_mfact=0.55
default_nmaster=1
smartgaps=0

# Dwindle Layout Setting
dwindle_smart_split=0
dwindle_drop_simple_split=1
dwindle_manual_split=0
dwindle_hsplit=1
dwindle_vsplit=1
dwindle_preserve_split=0

#dwindle layout(manual split mode)
bind=alt+shift,Return,dwindle_toggle_split_direction

# switch window status
bind=SUPER,g,toggleglobal,
bind=ALT,Tab,togglejump,
bind=ALT,backslash,togglefloating,
bind=ALT,a,togglemaximizescreen,
bind=ALT,f,togglefullscreen,
bind=ALT+SHIFT,f,togglefakefullscreen,
bind=SUPER,i,minimized,
bind=SUPER,o,toggleoverlay,
bind=SUPER+SHIFT,I,restore_minimized
bind=ALT,z,toggle_scratchpad

# movewin
bind=CTRL+SHIFT,Up,movewin,+0,-50
bind=CTRL+SHIFT,Down,movewin,+0,+50
bind=CTRL+SHIFT,Left,movewin,-50,+0
bind=CTRL+SHIFT,Right,movewin,+50,+0
# movewin (vim)
bind=CTRL+SHIFT,k,movewin,+0,-50
bind=CTRL+SHIFT,j,movewin,+0,+50
bind=CTRL+SHIFT,h,movewin,-50,+0
bind=CTRL+SHIFT,l,movewin,+50,+0

# resizewin
bind=CTRL+ALT,Up,resizewin,+0,-50
bind=CTRL+ALT,Down,resizewin,+0,+50
bind=CTRL+ALT,Left,resizewin,-50,+0
bind=CTRL+ALT,Right,resizewin,+50,+0
# resizewin (vim)
bind=CTRL+ALT,k,resizewin,+0,-50
bind=CTRL+ALT,j,resizewin,+0,+50
bind=CTRL+ALT,h,resizewin,-50,+0
bind=CTRL+ALT,l,resizewin,+50,+0
