bind=SUPER,period,spawn,noctalia msg panel-toggle session 
bind=SUPER,comma,spawn,noctalia msg settings-toggle

bind=NONE,XF86AudioRaiseVolume,spawn,noctalia msg volume-up
bind=NONE,XF86AudioLowerVolume,spawn,noctalia msg volume-down
bind=NONE,XF86AudioMute,spawn,noctalia msg volume-mute
bind=NONE,XF86MonBrightnessUp,spawn,noctalia msg brightness-up
bind=NONE,XF86MonBrightnessDown,spawn,noctalia msg brightness-down
bind=NONE,XF86AudioMicMute,spawn,noctalia msg mic-mute

