# Noctalia Theme for Mango
# Generated automatically by Noctalia Shell

shadowscolor = 0x000000ff
rootcolor = 0x000000ff
bordercolor = 0x5a5a5aff
dropcolor = 0xffffff80
splitcolor = 0xffffffff
focuscolor = 0xffffffff
maximizescreencolor = 0xf2f2f2ff
urgentcolor = 0xffffffff
scratchpadcolor = 0xffffffff
globalcolor = 0xb39898ff
overlaycolor = 0xa88989ff
jump_label_decorate_fg_color = 0xf5f5f5ff
jump_label_decorate_bg_color = 0x121212ff
jump_label_decorate_focus_fg_color = 0x000000ff
jump_label_decorate_focus_bg_color = 0xffffffff
jump_label_decorate_border_color = 0x5a5a5aff
