[audio]
sound_volume = 0.0

[bar.default]
end = [ "tray", "network", "volume", "battery", "bluetooth", "notifications" ]
margin_edge = 0
margin_ends = 0
padding = 5
panel_overlap = 0
radius = 0
scale = 1.3500000000000001
shadow = false
start = [ "workspaces" ]

[battery]
warning_threshold = 30

[control_center]
sidebar = "none"
sidebar_section = "none"

    [[control_center.shortcuts]]
    type = "wifi"

    [[control_center.shortcuts]]
    type = "bluetooth"

    [[control_center.shortcuts]]
    type = "caffeine"

    [[control_center.shortcuts]]
    type = "nightlight"

    [[control_center.shortcuts]]
    type = "notification"

[desktop_widgets]
enabled = false

[idle]
behavior_order = [ "lock", "screen-off", "lock-and-suspend" ]
pre_action_fade_seconds = 10

    [idle.behavior.lock]
    action = "lock"
    enabled = true
    timeout = 300.0

    [idle.behavior.lock-and-suspend]
    action = "lock_and_suspend"
    enabled = true
    timeout = 600.0

    [idle.behavior.screen-off]
    action = "screen_off"
    enabled = true
    timeout = 330.0

[location]
address = "Brooklyn NY"

[lockscreen_widgets]
enabled = false
schema_version = 2
widget_order = [ "lockscreen-login-box@HDMI-A-1", "lockscreen-login-box@eDP-1" ]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-1"]
    box_height = 70.0
    box_width = 400.0
    cx = 840.0
    cy = 931.0
    output = "HDMI-A-1"
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        input_opacity = 1.0
        input_radius = 6.0
        show_login_button = true

    [lockscreen_widgets.widget."lockscreen-login-box@eDP-1"]
    box_height = 70.0
    box_width = 400.0
    cx = 960.0
    cy = 961.0
    output = "eDP-1"
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@eDP-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        input_opacity = 1.0
        input_radius = 6.0
        show_login_button = true

[nightlight]
temperature_day = 4500
temperature_night = 2700

[osd]
orientation = "vertical"
position = "top_right"
position_vertical = "top_right"

[shell]
clipboard_enabled = false
font_family = "Iosevka Fixed"
offline_mode = true
settings_show_advanced = true
show_location = false
time_format = "{: %I:%M %p}"
ui_scale = 1.1499999999999999

    [shell.animation]
    enabled = false
    speed = 0.10000000149011612

    [shell.panel]
    open_near_click_control_center = true

    [shell.screenshot]
    copy_to_clipboard = false
    freeze_screen = false
    save_to_file = false

    [[shell.session.actions]]
    action = "command"
    command = "noctalia msg session lock && systemctl hibernate"
    countdown_seconds = 0.0
    enabled = true
    glyph = "weather-moon"
    label = "Hibernate"
    shortcut = "1"
    variant = "default"

    [[shell.session.actions]]
    action = "lock"
    countdown_seconds = 0.0
    enabled = true
    shortcut = "2"
    variant = "default"

    [[shell.session.actions]]
    action = "logout"
    countdown_seconds = 0.0
    enabled = false
    shortcut = "2"
    variant = "default"

    [[shell.session.actions]]
    action = "lock_and_suspend"
    countdown_seconds = 0.0
    enabled = true
    shortcut = "3"
    variant = "default"

    [[shell.session.actions]]
    action = "reboot"
    countdown_seconds = 0.0
    enabled = true
    shortcut = "4"
    variant = "default"

    [[shell.session.actions]]
    action = "shutdown"
    countdown_seconds = 0.0
    enabled = true
    shortcut = "5"
    variant = "destructive"

    [shell.shadow]
    alpha = 0.0

[system.monitor]
cpu_poll_seconds = 0
disk_poll_seconds = 0
enabled = false
memory_poll_seconds = 0
network_poll_seconds = 0

[theme]
builtin = "Ayu"
community_palette = "Lilac AMOLED"
custom_palette = "MonochromeAMOLED"
source = "custom"

    [theme.templates]
    builtin_ids = [ "alacritty", "emacs", "mango" ]

[wallpaper]
enabled = false
fill_mode = "fit"
transition = [ "disc" ]

[weather]
effects = false
unit = "imperial"

[widget.clock]
format = "{: %I:%M %p}"