# --- Autostart ---
# syncthing
exec-once=/mnt/backup/Downloads/Syncthing/syncthing

# dms
exec-once=dms run

# fcitx5
exec-once=fcitx5

# dms mic led
exec-once=sleep 6 && dms ipc brightness set 0 leds:platform::micmute

# bluetooth off
exec-once=sleep 2 && bluetooth off

# --- Emacs ---
exec-once=emacs --daemon

# --- Proton VPN ---
# ---


# --- Worksapce assigned apps ---
# ---
