# Key Bindings
# key name refer to `xev` or `wev` command output,
# mod keys name: super,ctrl,alt,shift,none

# --- General Binds ---
# reload config
bind=SUPER,r,reload_config

# exit
bind=SUPER,e,quit
bind=SUPER,q,killclient,
# ---

# --- App binds ----
# Terminal
bind=SUPER,Return,spawn,alacritty

# File Manager
bind=SUPER,f,spawn,thunar

# T14 bind
bind=none,XF86FAVORITES,spawn,emacsclient -c

# Browser
bind=SUPER,b,spawn,env MOZ_ENABLE_WAYLAND=1 librewolf
# ---

# --- Layout Binds ---
# switch layout
bind=SUPER,n,switch_layout

# Mouse Button Bindings
# btn_left and btn_right can't bind none mod key
mousebind=SUPER,btn_left,moveresize,curmove
mousebind=NONE,btn_middle,togglemaximizescreen,0
mousebind=SUPER,btn_right,moveresize,curresize
# ---