bind=SUPER,period,spawn,dms ipc powermenu toggle
bind=SUPER,comma,spawn,dms ipc settings toggle

bind=NONE,XF86AudioRaiseVolume,spawn,dms ipc audio increment 5
bind=NONE,XF86AudioLowerVolume,spawn,dms ipc audio decrement 5
bind=NONE,XF86AudioMute,spawn,dms ipc audio micmute

bind=NONE,XF86MonBrightnessUp,spawn,dms ipc brightness increment 5 backlight:amdgpu_bl1
bind=NONE,XF86MonBrightnessDown,spawn,dms ipc brightness decrement 5 backlight:amdgpu_bl1

bind=SUPER,d,spawn,dms ipc spotlight-bar toggle
