# Open emacs keybind
# Setup emacs daemon with (/usr/bin/emacs --daemon &)
# run emacs using (emacsclient -c)
exec emacs --daemon
bindsym XF86FAVORITES exec emacsclient -c 

# Autotiling (Look in dotfiles for setup)
exec_always autotiling

# Proton VPN
# exec_always --no-startup-id /usr/bin/protonvpn-app
for_window [app_id="proton.vpn.app.gtk"] move to workspace 10

# Noctalia Bar
exec qs -c noctalia-shell