set $term ghostty
set $menu rofi -show drun
bindsym $mod+Return exec $term
bindsym $mod+Shift+q kill
bindsym $mod+d exec $menu
bindsym $mod+comma exec $ipc settings-toggle
bindsym $mod+period exec $ipc panel-toggle session
bindsym $mod+Shift+c reload
# Screenshot
bindsym Print exec grim
# Move focus to the parent container
bindsym $mod+a focus parent

